EMS/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('Employee.urls')),
]

Employee/urls.py
from django.urls import path
from Employee import views

urlpatterns = [
    path("",views.emp),
    path("show",views.show),
    path("edit/<int:id>",views.edit),
    path("update/<int:id>",views.update),
    path("delete/<int:id>",views.destroy),

    path("basic",views.basic),

]

Employee/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    emp_id = models.CharField(unique=True,max_length=10)
    emp_fname = models.CharField(max_length=20,default="")
    emp_lname = models.CharField(max_length=20,default="")
    emp_email = models.EmailField()
    emp_mobile = models.CharField(max_length=12)
    emp_address = models.TextField(max_length=200)


    def __str__(self):
        return "Emp_id : "+self.emp_id

Employee/forms.py
from django import forms
from Employee.models import Employee

class Emp_form(forms.ModelForm):

    class Meta:
        model = Employee
        fields = "__all__"

Employee/views.py
from django.shortcuts import render , redirect,HttpResponse
from Employee.forms import Emp_form
from Employee.models import Employee


# Create your views here.


def emp(request):
    if request.method == "POST":
        # initiate form
        form = Emp_form(request.POST)
        
        if form.is_valid():
            try :
            
                form.save()
                return redirect("/show")

            except:
                print("some error occured")    
        
        else :
            return HttpResponse("Employed id alreday exits!")
    else :
        form = Emp_form()
        return render(request,"Employee/index.html",{"form_html":form})


def show(request):
    all_emp = Employee.objects.all()

    return render(request,"Employee/show.html",{"all_emp":all_emp})


def edit(request,id):
    employee = Employee.objects.get(id = id)

    return render(request,"Employee/edit.html",{"employee":employee})


def update(request,id):


    employee = Employee.objects.get(id=id)  
    # filled the form with selected employee
    print(employee)
    form = Emp_form(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show")  

    else : 
        print("error")    
    return render(request, 'Employee/edit.html', {'employee': employee}) 



def destroy(request,id):
    emp_del = Employee.objects.get(id = id)
    emp_del.delete()

    return redirect("/show")



def basic(request):
    return render(request,"Employee/basic.html")

Employee/templates/Employee/basic.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'Employee/css/style2.css'%}">
    <title> {% block title %}  {% endblock %} </title>
    <style> 
 
    {% block css %} 

 
     {% endblock %} 
     </style>

  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="#">Employee Management System</a>
  
  <!-- Links -->
  {% block links %}

  {% endblock %}

</nav>



  {% block body %} 
  {% endblock %}

  {% block abc %}
  
  {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- We are declaring the js block at the bottom because we want to use jquery cdn link as well-->

    {% block js %}
    {% comment %} Javascript Code here {% endcomment %}
    {% endblock %}
  </body>
</html>

Employee/templates/Employee/edit.html
{% extends 'Employee/basic.html'%}

{% block links%}

<span class="nav">
<ul class="navbar-nav">

    
    <li class="nav-item">
      <a class="nav-link text-primary" href="/show">Employee List</a>
    </li>
  </ul> 
  </span>
{% endblock %}

{% block css%}

.form-control
{
    display: block;
    width: 50%;
    margin: auto;
}

.btn-block {
    display: block;
    width: 50%;
    margin: auto;
}

h3{
  
    width: 30%;
    display: block;
    margin: auto;
}

{% endblock %}

{% block body %} 


    <div class="container mt-5">
  <h3>Update Employee Details</h3>
  
<form method="POST"  action="/update/{{employee.id}}">  
        {% csrf_token %}  

    <div class="form-group col-xs-4">

     
      <input type="text"  class="form-control" name="emp_id" id="id_emp_id" required maxlength="20" value="{{ employee.emp_id }}" placeholder ="Enter Employee Id"/>  

    </div>

    <div class="form-group">


      <input type="text"  class="form-control" name="emp_fname" id="id_emp_fname" required maxlength="20" value="{{ employee.emp_fname }}"
      placeholder ="Enter First Name"/>  
      
    </div>


    <div class="form-group">

   
      <input type="text"  class="form-control" name="emp_lname" id="id_emp_lname" required maxlength="20" value="{{ employee.emp_lname }}"
      placeholder ="Enter Last Name"/>  
      
    </div>


    <div class="form-group">

      <input type="email"  class="form-control" name="emp_email" id="id_emp_email" required maxlength="30" value="{{ employee.emp_email }}"
      placeholder ="Enter Email"/>  
      
    </div>


    <div class="form-group">
      <input type="text"  class="form-control" name="emp_mobile" id="id_emp_mobile" required maxlength="10" minlength="9" value="{{ employee.emp_mobile }}"
      placeholder ="Enter Mobile No"/>  
      
    </div>


   <div class="form-group">

      <textarea rows="5" class="form-control" name="emp_address" id="id_emp_address" required maxlength="200" placeholder ="Enter Address">
      {{ employee.emp_address }}
      </textarea>


    
    </div>
  
    <button type="submit" class="btn btn-success btn-block">Submit</button>
  </form>
</div>

{% endblock %}

Employee/templates/Employee/index.html
{% extends "Employee/basic.html"%}

{% block links%}

<div class="nav">
<ul class="navbar-nav">

    
    <li class="nav-item">
      <a class="nav-link text-primary" href="/show">Employee List</a>
    </li>
  </ul> 
  </div>
{% endblock %}

{% block css %}

@media screen and (min-width: 1110px) {
  .btn {
    color: cyan;
    margin-left:200px;
  }
}
{% endblock %}

{% block body %}

<form method="POST" class="post-form" action="/">

  {% csrf_token %}
  <div class="container">
    <br>
    <div class="form-group row">
      <label class="col-sm-1 col-form-label"></label>
      <div class="col-sm-4">
        <h3>Enter Details</h3>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Employee Id:</label>
      <div class="col-sm-4">
        {{ form_html.emp_id }}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">First Name:</label>
      <div class="col-sm-4">
        {{ form_html.emp_fname }}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Last Name:</label>
      <div class="col-sm-4">
        {{ form_html.emp_lname }}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Email:</label>
      <div class="col-sm-4">
        {{ form_html.emp_email }}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Mobile :</label>
      <div class="col-sm-4">
        {{ form_html.emp_mobile}}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-2 col-form-label">Address:</label>
      <div class="col-sm-4">
        {{ form_html.emp_address}}
      </div>
    </div>
    <div class="form-group row">
       <label class="col-sm-2 col-form-label"></label>
        <button type="submit" class="btn btn-success">Add Employee</button>
    
    </div>
  </div>
</form>

{% endblock %}

Employee/templates/Employee/show.html
{% extends "Employee/basic.html"%}

{% block body %}

<div class="table-wrap">
 <table class="table table-bordered table-responsive-md table-responsive-sm  table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Employee ID</th>  
        <th>First Name</th>  
        <th>Last Name</th>  
        <th>Email</th>  
        <th>Contact</th>  
        <th>Actions</th>  
      </tr>
    </thead>
    <tbody>
     {% for employee in all_emp %}  
    <tr class="hover-tr">  
        <td>{{ employee.emp_id }}</td>  
        <td>{{ employee.emp_fname }}</td>  
        <td>{{ employee.emp_lname }}</td>  

        <td>{{ employee.emp_email }}</td>  
        <td>{{ employee.emp_mobile }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="btn btn-primary" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}" class="btn btn-danger">Delete</a>  
        </td>  
    </tr>  
{% endfor %} 
    </tbody>
  </table>
</div>
 
<br>  
<br>  
<center><a href="/" class="btn btn-success">Add New Record</a></center>  


{% endblock %}